/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameVehiculo;

import SistemaCinturones.Cinturon;
import SistemaCinturones.Control_Cinturones;
import SistemaEncendido.Motor;
import SistemaIluminacion.IntermitentesyEmergencia;
import SistemaIluminacion.LucesPuertas;
import SistemaIluminacion.LuzAlta;
import SistemaIluminacion.LuzBaja;
import SistemaRadio.Radio;
import SistemaClimatizacion.Climatizacion;
import SistemaKilometraje.Kilometraje;

/**
 *
 * @author Luisf
 */
public class Vehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vehiculo.class.getName());
    private Motor motor = new Motor();
    private LuzBaja luzBaja = new LuzBaja();
    private LuzAlta luzAlta = new LuzAlta();
    private IntermitentesyEmergencia intermitentes = new IntermitentesyEmergencia();
    private LucesPuertas puertaIzq = new LucesPuertas("izquierda");
    private LucesPuertas puertaDer = new LucesPuertas("derecha");
    private boolean PuerIzqAbierta = false;
    private boolean PuerDerAbierta = false;
    private Radio radio = new Radio();
    private Climatizacion climatizacion = new Climatizacion();
    private Kilometraje kilometraje;
    private Control_Cinturones chofer;
     private Control_Cinturones copiloto;
     private SistemaCombustible.Combustible combustible;

    /**
     * Creates new form Vehiculo
     */
    public Vehiculo() {
        initComponents();
        lblLuzBaja.setVisible(false);
        lblLuzAlta.setVisible(false);
        lblIntIzq.setVisible(false);
        lblIntDer.setVisible(false);
        lblMotor.setVisible(false);
        lblPuertIzq.setVisible(false);
        lblPuertDer.setVisible(false);
        lblLuzPuertas.setVisible(false);
        lblRadio.setVisible(false);
        lblVentilacion.setVisible(false);
        lblAC.setVisible(false);
        lblCalefaccion.setVisible(false);
      combustible = new SistemaCombustible.Combustible();
      kilometraje = new SistemaKilometraje.Kilometraje(combustible);    // Nivel 100%

    
// Configurar la barra de combustible
jProgressBarCombustible.setMinimum(0);
jProgressBarCombustible.setMaximum(100);
jProgressBarCombustible.setValue((int) combustible.getNivel()); // 🔹 Arranca llena
jProgressBarCombustible.setStringPainted(true); // Muestra el porcentaje

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMotor = new javax.swing.JToggleButton();
        chkLuzBaja = new javax.swing.JCheckBox();
        chkLuzAlta = new javax.swing.JCheckBox();
        chkIntIzqui = new javax.swing.JCheckBox();
        chkIntDer = new javax.swing.JCheckBox();
        btnEmergencia = new javax.swing.JToggleButton();
        btnPuerDerecha = new javax.swing.JButton();
        lblLuzDer = new javax.swing.JLabel();
        btnPuerIzqui = new javax.swing.JButton();
        lblLuzIz = new javax.swing.JLabel();
        lblLuzBaja = new javax.swing.JLabel();
        lblLuzAlta = new javax.swing.JLabel();
        lblIntDer = new javax.swing.JLabel();
        lblIntIzq = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblPuertIzq = new javax.swing.JLabel();
        lblPuerIzq = new javax.swing.JLabel();
        lblPuertDer = new javax.swing.JLabel();
        lblPuerDer = new javax.swing.JLabel();
        lblLuzPuertas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnRadioEncender = new javax.swing.JButton();
        btnCambiarModo = new javax.swing.JButton();
        lblEstadoRadio = new javax.swing.JLabel();
        btnEncenderClima = new javax.swing.JButton();
        lblEstadoClima = new javax.swing.JLabel();
        btnSubirTemp = new javax.swing.JButton();
        btnBajarTemp = new javax.swing.JButton();
        btnCambiarVelocidad = new javax.swing.JButton();
        bntAC = new javax.swing.JButton();
        btnCalefaccion = new javax.swing.JButton();
        lblRadio = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblVentilacion = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblCalefaccion = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        lblVelocidad = new javax.swing.JLabel();
        lblRPM = new javax.swing.JLabel();
        lblKMH = new javax.swing.JLabel();
        btnCchofer = new javax.swing.JButton();
        btnCcopiloto = new javax.swing.JButton();
        IblCchofer = new javax.swing.JLabel();
        IblCcopiloto = new javax.swing.JLabel();
        jProgressBarCombustible = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        btnMotor.setText("Encender Motor");
        btnMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorActionPerformed(evt);
            }
        });

        chkLuzBaja.setBackground(new java.awt.Color(255, 255, 255));
        chkLuzBaja.setText("Luz Baja");
        chkLuzBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzBajaActionPerformed(evt);
            }
        });

        chkLuzAlta.setBackground(new java.awt.Color(255, 255, 255));
        chkLuzAlta.setText("Luz Alta");
        chkLuzAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzAltaActionPerformed(evt);
            }
        });

        chkIntIzqui.setBackground(new java.awt.Color(255, 255, 255));
        chkIntIzqui.setText("Int Izquierda");
        chkIntIzqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntIzquiActionPerformed(evt);
            }
        });

        chkIntDer.setBackground(new java.awt.Color(255, 255, 255));
        chkIntDer.setText("Int Derecha");
        chkIntDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntDerActionPerformed(evt);
            }
        });

        btnEmergencia.setText("Emergencia");
        btnEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergenciaActionPerformed(evt);
            }
        });

        btnPuerDerecha.setText("Abrir/Cerrar PuerDerecha");
        btnPuerDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerDerechaActionPerformed(evt);
            }
        });

        lblLuzDer.setBackground(new java.awt.Color(255, 255, 255));
        lblLuzDer.setText("Luz PuerDerecha OFF");
        lblLuzDer.setOpaque(true);

        btnPuerIzqui.setText("Abrir/Cerrar PuerIzquierda");
        btnPuerIzqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerIzquiActionPerformed(evt);
            }
        });

        lblLuzIz.setBackground(new java.awt.Color(255, 255, 255));
        lblLuzIz.setText("Luz PuerIzquierda OFF");
        lblLuzIz.setOpaque(true);

        lblLuzBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/LuzBaja.png"))); // NOI18N

        lblLuzAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/LuzAlta.png"))); // NOI18N

        lblIntDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/IntDerecha.png"))); // NOI18N

        lblIntIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/IntIzquierda.png"))); // NOI18N

        lblMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Motor.png"))); // NOI18N

        lblPuertIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaAbierta.png"))); // NOI18N

        lblPuerIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaCerrada.png"))); // NOI18N

        lblPuertDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaAbierta.png"))); // NOI18N

        lblPuerDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaCerrada.png"))); // NOI18N

        lblLuzPuertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Luz.png"))); // NOI18N

        btnRadioEncender.setText("Encender/Apagar Radio");
        btnRadioEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioEncenderActionPerformed(evt);
            }
        });

        btnCambiarModo.setText("Cambiar Modo");
        btnCambiarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarModoActionPerformed(evt);
            }
        });

        lblEstadoRadio.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoRadio.setText("Estado Radio");
        lblEstadoRadio.setOpaque(true);

        btnEncenderClima.setText("Encender/Apagar Clima");
        btnEncenderClima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderClimaActionPerformed(evt);
            }
        });

        lblEstadoClima.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoClima.setText("Estado Clima");
        lblEstadoClima.setOpaque(true);

        btnSubirTemp.setText("+");
        btnSubirTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirTempActionPerformed(evt);
            }
        });

        btnBajarTemp.setText("-");
        btnBajarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarTempActionPerformed(evt);
            }
        });

        btnCambiarVelocidad.setText("Cambiar Velocidad");
        btnCambiarVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVelocidadActionPerformed(evt);
            }
        });

        bntAC.setText("A/C");
        bntAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntACActionPerformed(evt);
            }
        });

        btnCalefaccion.setText("Calefaccion");
        btnCalefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalefaccionActionPerformed(evt);
            }
        });

        lblRadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/RadioEncendido.png"))); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblVentilacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Ventilacion.png"))); // NOI18N

        lblAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/AC.png"))); // NOI18N

        lblCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Calefaccion.png"))); // NOI18N

        btnAcelerar.setText("Acelerar");
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });

        btnFrenar.setText("Frenar");
        btnFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenarActionPerformed(evt);
            }
        });

        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        lblVelocidad.setBackground(new java.awt.Color(255, 255, 255));
        lblVelocidad.setText("Velocidad");
        lblVelocidad.setOpaque(true);

        lblRPM.setBackground(new java.awt.Color(255, 255, 255));
        lblRPM.setText("RPM");
        lblRPM.setOpaque(true);

        lblKMH.setBackground(new java.awt.Color(255, 255, 255));
        lblKMH.setText("KMH");
        lblKMH.setOpaque(true);

        btnCchofer.setText("Chofer");
        btnCchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCchoferActionPerformed(evt);
            }
        });

        btnCcopiloto.setText("copiloto");
        btnCcopiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCcopilotoActionPerformed(evt);
            }
        });

        jProgressBarCombustible.setOrientation(1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(chkLuzAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkIntDer, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(chkLuzBaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkIntIzqui, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMotor)
                    .addComponent(lblMotor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIntDer, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblPuertIzq)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblPuertDer))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblPuerIzq)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblPuerDer))
                                    .addComponent(lblLuzAlta, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(lblLuzBaja)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstadoRadio))
                                .addGap(46, 46, 46)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(IblCcopiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(IblCchofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblKMH))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblVentilacion)
                                                        .addComponent(lblCalefaccion, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(lblAC)
                                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(260, 260, 260))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblEstadoClima)
                                                .addGap(115, 115, 115)
                                                .addComponent(lblVelocidad)
                                                .addGap(56, 56, 56)
                                                .addComponent(lblRPM)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCcopiloto))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblLuzPuertas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPuerIzqui)
                                .addComponent(btnPuerDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIntIzq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLuzDer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuzIz, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRadioEncender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEncenderClima))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCambiarModo)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSubirTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCambiarVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnBajarTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCalefaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bntAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAcelerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFrenar))
                            .addComponent(btnAvanzar))
                        .addGap(32, 32, 32)
                        .addComponent(jProgressBarCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCchofer)))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntDer)
                    .addComponent(lblIntIzq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(lblLuzPuertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(lblCalefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPuerIzq))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPuerDer)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuertDer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPuertIzq, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IblCchofer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCcopiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IblCcopiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCchofer)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPuerIzqui)
                                    .addComponent(lblLuzIz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCambiarModo)
                                    .addComponent(btnSubirTemp)
                                    .addComponent(btnCambiarVelocidad)
                                    .addComponent(btnAvanzar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkLuzAlta)
                                    .addComponent(chkIntDer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBajarTemp)
                                    .addComponent(bntAC)))
                            .addComponent(lblMotor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMotor)
                            .addComponent(chkLuzBaja)
                            .addComponent(chkIntIzqui, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalefaccion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblLuzAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRadio)
                                    .addComponent(lblVentilacion))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEstadoRadio)
                                    .addComponent(lblEstadoClima)
                                    .addComponent(lblVelocidad)
                                    .addComponent(lblRPM)
                                    .addComponent(lblKMH))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(lblLuzBaja)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLuzDer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPuerDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRadioEncender)
                                    .addComponent(btnEncenderClima)
                                    .addComponent(btnAcelerar)
                                    .addComponent(btnFrenar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jProgressBarCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorActionPerformed
        if (!motor.isEstado()) {
            motor.encender();
            btnMotor.setText("Apagar el motor");
            lblMotor.setVisible(true);
        } else {
            motor.apagar();
            btnMotor.setText("Encender el motor");
            chkLuzAlta.setSelected(false);
            chkLuzBaja.setSelected(false);
            chkIntDer.setSelected(false);
            chkIntIzqui.setSelected(false);
            btnEmergencia.setSelected(false);

            luzAlta.apagar();
            luzBaja.apagar();
            intermitentes.apagarEmergencia();
            intermitentes.apagarIntizquierda();
            intermitentes.apagarIntderecha();

            lblMotor.setVisible(false);
            lblLuzAlta.setVisible(false);
            lblLuzBaja.setVisible(false);
            lblIntDer.setVisible(false);
            lblIntIzq.setVisible(false);
        }
    }//GEN-LAST:event_btnMotorActionPerformed

    private void chkLuzBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzBajaActionPerformed
        if (!motor.isEstado()) {
            chkLuzBaja.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la luz baja");
            return;
        }
        if (chkLuzBaja.isSelected()) {
            if (chkLuzAlta.isSelected()) {
                chkLuzAlta.setSelected(false);
                luzAlta.apagar();
                lblLuzAlta.setVisible(false);
            }
            luzBaja.encender(motor);
            lblLuzBaja.setVisible(true);
        } else {
            luzBaja.apagar();
            lblLuzBaja.setVisible(false);
        }
    }//GEN-LAST:event_chkLuzBajaActionPerformed

    private void chkLuzAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzAltaActionPerformed
        if (!motor.isEstado()) {
            chkLuzAlta.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la luz alta");
            return;
        }
        if (chkLuzAlta.isSelected()) {
            if (chkLuzBaja.isSelected()) {
                chkLuzBaja.setSelected(false);
                luzBaja.apagar();
                lblLuzBaja.setVisible(false);
            }
            luzAlta.encender(motor);
            lblLuzAlta.setVisible(true);
        } else {
            luzAlta.apagar();
            lblLuzAlta.setVisible(false);
        }
    }//GEN-LAST:event_chkLuzAltaActionPerformed

    private void btnEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergenciaActionPerformed
        if (!motor.isEstado()) {
            btnEmergencia.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para usar luces de emergencia");
            return;
        }
        if (btnEmergencia.isSelected()) {
            if (chkIntIzqui.isSelected() || chkIntDer.isSelected()) {
                btnEmergencia.setSelected(false);
                javax.swing.JOptionPane.showMessageDialog(this, "Apaga las intermitentes para activar las luces de emergencia");
                return;
            }
            intermitentes.activarEmergencia(motor);
            chkIntIzqui.setSelected(true);
            chkIntDer.setSelected(true);
            btnEmergencia.setText("Apagar emergencia");
            lblIntIzq.setVisible(true);
            lblIntDer.setVisible(true);
        } else {
            intermitentes.apagarEmergencia();
            chkIntIzqui.setSelected(false);
            chkIntDer.setSelected(false);
            btnEmergencia.setText("Encender emergencia");
            lblIntIzq.setVisible(false);
            lblIntDer.setVisible(false);
        }
    }//GEN-LAST:event_btnEmergenciaActionPerformed

    private void chkIntIzquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntIzquiActionPerformed
        if (!motor.isEstado()) {
            chkIntIzqui.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la intermitente izquierda");
            return;
        }
        if (chkIntIzqui.isSelected()) {
            if (chkIntDer.isSelected()) {
                chkIntDer.setSelected(false);
                intermitentes.apagarIntderecha();
                lblIntDer.setVisible(false);
            }
            intermitentes.encenderIntizquierda(motor);
            lblIntIzq.setVisible(true);
        } else {
            intermitentes.apagarIntizquierda();
            lblIntIzq.setVisible(false);
        }
    }//GEN-LAST:event_chkIntIzquiActionPerformed

    private void chkIntDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntDerActionPerformed
        if (!motor.isEstado()) {
            chkIntDer.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la intermitente derecha");
            return;
        }
        if (chkIntDer.isSelected()) {
            if (chkIntIzqui.isSelected()) {
                chkIntIzqui.setSelected(false);
                intermitentes.apagarIntizquierda();
                lblIntIzq.setVisible(false);
            }
            intermitentes.encenderIntderecha(motor);
            lblIntDer.setVisible(true);
        } else {
            intermitentes.apagarIntderecha();
            lblIntDer.setVisible(false);
        }   
    }//GEN-LAST:event_chkIntDerActionPerformed

    private void btnPuerIzquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerIzquiActionPerformed
        if (!PuerIzqAbierta) {
            puertaIzq.abrirPuerta();
            lblLuzIz.setText("Luz PuerIzquierda encendida");
            btnPuerIzqui.setText("Cerrar PuerIzquierda");
            PuerIzqAbierta = true;
            lblPuertIzq.setVisible(true);
            lblPuerIzq.setVisible(false); 
        } else {
            puertaIzq.cerrarPuerta();
            lblLuzIz.setText("Luz PuerIzquierda apagada");
            btnPuerIzqui.setText("Abrir PuerIzquierda");
            PuerIzqAbierta = false;
            lblPuertIzq.setVisible(false);
            lblPuerIzq.setVisible(true);
        }
        if (PuerIzqAbierta || PuerDerAbierta) {
            lblLuzPuertas.setVisible(true);
        } else {
            lblLuzPuertas.setVisible(false);
        }
    }//GEN-LAST:event_btnPuerIzquiActionPerformed

    private void btnPuerDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerDerechaActionPerformed
        if (!PuerDerAbierta) {
            puertaDer.abrirPuerta();
            lblLuzDer.setText("Luz PuerDerecha encendida");
            btnPuerDerecha.setText("Cerrar PuerDerecha");
            PuerDerAbierta = true;
            lblPuertDer.setVisible(true);
            lblPuerDer.setVisible(false);
            lblLuzPuertas.setVisible(true);
        } else {
            puertaDer.cerrarPuerta();
            lblLuzDer.setText("Luz PuerDerecha apagada");
            btnPuerDerecha.setText("Abrir PuerDerecha");
            PuerDerAbierta = false;
            lblPuertDer.setVisible(false);
            lblPuerDer.setVisible(true);
            lblLuzPuertas.setVisible(false);
        }
        if (PuerIzqAbierta || PuerDerAbierta) {
            lblLuzPuertas.setVisible(true);
        } else {
            lblLuzPuertas.setVisible(false);
        }
    }//GEN-LAST:event_btnPuerDerechaActionPerformed

    private void btnCambiarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarModoActionPerformed
        radio.CambiarModo();
        lblEstadoRadio.setText(radio.getEstado());
    }//GEN-LAST:event_btnCambiarModoActionPerformed

    private void btnRadioEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioEncenderActionPerformed
        if (!radio.isEstado()){
            radio.encender();
            lblEstadoRadio.setVisible(true);
            lblEstadoRadio.setText("Radio Encendido");
            lblRadio.setVisible(true);
        }else{
            radio.apagar();
            lblEstadoRadio.setVisible(false);
            lblEstadoRadio.setText("Radio Apagado");
            lblRadio.setVisible(false);
        }
        lblEstadoRadio.setText(radio.getEstado());
    }//GEN-LAST:event_btnRadioEncenderActionPerformed

    private void btnEncenderClimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderClimaActionPerformed
        if(!climatizacion.isEstado()){
            climatizacion.encender();
            lblEstadoClima.setVisible(true);
            lblEstadoClima.setText("Clima Encendido");
            lblVentilacion.setVisible(true);
        }else{
            climatizacion.apagar();
            lblEstadoClima.setVisible(false);
            lblEstadoClima.setText("Clima Apagado");
            lblVentilacion.setVisible(false);
        }
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_btnEncenderClimaActionPerformed

    private void btnSubirTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirTempActionPerformed
        climatizacion.subirTemp();
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_btnSubirTempActionPerformed

    private void btnBajarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarTempActionPerformed
        climatizacion.bajarTemp();
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_btnBajarTempActionPerformed

    private void btnCambiarVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVelocidadActionPerformed
        climatizacion.cambiarVelocidad();
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_btnCambiarVelocidadActionPerformed

    private void bntACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntACActionPerformed
        if(climatizacion.isAcActivo()){
            climatizacion.apagar();
            bntAC.setText("Encender A/C");
            btnCalefaccion.setText("Encender Calefaccion");
            lblAC.setVisible(false);
        }else{
            climatizacion.encender();
            climatizacion.encenderAC();
            bntAC.setText("Apagar A/C");
            btnCalefaccion.setText("Encender Calefaccion");
            lblAC.setVisible(true);
        }
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_bntACActionPerformed

    private void btnCalefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalefaccionActionPerformed
        if(climatizacion.isCalefaccionActiva()){
            climatizacion.apagar();
            btnCalefaccion.setText("Encender Calefaccion");
            bntAC.setText("Encender A/C");
            lblCalefaccion.setVisible(false);
        }else{
            climatizacion.encender();
            climatizacion.encenderCalefaccion();
            btnCalefaccion.setText("Apagar Calefaccion");
            bntAC.setText("Encender A/C");
            lblCalefaccion.setVisible(true);
        }
        lblEstadoClima.setText(climatizacion.getEstado());
    }//GEN-LAST:event_btnCalefaccionActionPerformed

    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        kilometraje.acelerar();
        lblVelocidad.setText("Velocidad: " + kilometraje.getVelocidadActual() + "KM/H");
        lblRPM.setText("RPM: " + kilometraje.getRpm());
        lblKMH.setText("KM/H: " + kilometraje.getKmhTotales());
        jProgressBarCombustible.setValue((int) kilometraje.getCombustible().getNivel());
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenarActionPerformed
        kilometraje.frenar();
        lblVelocidad.setText("Velocidad: " + kilometraje.getVelocidadActual() + "KM/H");
        lblRPM.setText("RPM: " + kilometraje.getRpm());
        lblKMH.setText("KM/H: " + kilometraje.getKmhTotales());
    }//GEN-LAST:event_btnFrenarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        kilometraje.avanzar(5);
        lblVelocidad.setText("Velocidad: " + kilometraje.getVelocidadActual() + "KM/H");
        lblRPM.setText("RPM: " + kilometraje.getRpm());
        lblKMH.setText("KM/H: " + kilometraje.getKmhTotales());
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnCchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCchoferActionPerformed
    Cinturon cinturonChofer = chofer.getIzquierdo();
    if(cinturonChofer.getSensor().isCinturon()){
        cinturonChofer.quitar();
        btnCchofer.setText("poner sinturon");
        IblCchofer.setText("Cinturon:Desabrochado");
        
    }else{cinturonChofer.poner();
    btnCchofer.setText("quitar cinturon");
     IblCchofer.setText("Cinturon:abrochado");   
    }
    }//GEN-LAST:event_btnCchoferActionPerformed

    private void btnCcopilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCcopilotoActionPerformed
        Cinturon cinturonCopiloto = chofer.getDerecho();
    if(cinturonCopiloto.getSensor().isCinturon()){
        cinturonCopiloto.quitar();
        btnCchofer.setText("poner sinturon");
        IblCcopiloto.setText("Cinturon:Desabrochado");
        
    }else{cinturonCopiloto.poner();
    btnCchofer.setText("quitar cinturon");
    IblCcopiloto.setText("Cinturon:abrochado");  
        
    }
    }//GEN-LAST:event_btnCcopilotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblCchofer;
    private javax.swing.JLabel IblCcopiloto;
    private javax.swing.JButton bntAC;
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnBajarTemp;
    private javax.swing.JButton btnCalefaccion;
    private javax.swing.JButton btnCambiarModo;
    private javax.swing.JButton btnCambiarVelocidad;
    private javax.swing.JButton btnCchofer;
    private javax.swing.JButton btnCcopiloto;
    private javax.swing.JToggleButton btnEmergencia;
    private javax.swing.JButton btnEncenderClima;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JToggleButton btnMotor;
    private javax.swing.JButton btnPuerDerecha;
    private javax.swing.JButton btnPuerIzqui;
    private javax.swing.JButton btnRadioEncender;
    private javax.swing.JButton btnSubirTemp;
    private javax.swing.JCheckBox chkIntDer;
    private javax.swing.JCheckBox chkIntIzqui;
    private javax.swing.JCheckBox chkLuzAlta;
    private javax.swing.JCheckBox chkLuzBaja;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBarCombustible;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblCalefaccion;
    private javax.swing.JLabel lblEstadoClima;
    private javax.swing.JLabel lblEstadoRadio;
    private javax.swing.JLabel lblIntDer;
    private javax.swing.JLabel lblIntIzq;
    private javax.swing.JLabel lblKMH;
    private javax.swing.JLabel lblLuzAlta;
    private javax.swing.JLabel lblLuzBaja;
    private javax.swing.JLabel lblLuzDer;
    private javax.swing.JLabel lblLuzIz;
    private javax.swing.JLabel lblLuzPuertas;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblPuerDer;
    private javax.swing.JLabel lblPuerIzq;
    private javax.swing.JLabel lblPuertDer;
    private javax.swing.JLabel lblPuertIzq;
    private javax.swing.JLabel lblRPM;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JLabel lblVentilacion;
    // End of variables declaration//GEN-END:variables
}
