/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameVehiculo;

import SistemaEncendido.Motor;
import SistemaIluminacion.IntermitentesyEmergencia;
import SistemaIluminacion.LucesPuertas;
import SistemaIluminacion.LuzAlta;
import SistemaIluminacion.LuzBaja;

/**
 *
 * @author Luisf
 */
public class Vehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vehiculo.class.getName());
    private Motor motor = new Motor();
    private LuzBaja luzBaja = new LuzBaja();
    private LuzAlta luzAlta = new LuzAlta();
    private IntermitentesyEmergencia intermitentes = new IntermitentesyEmergencia();
    private LucesPuertas puertaIzq = new LucesPuertas("izquierda");
    private LucesPuertas puertaDer = new LucesPuertas("derecha");
    private boolean PuerIzqAbierta = false;
    private boolean PuerDerAbierta = false;
    /**
     * Creates new form Vehiculo
     */
    public Vehiculo() {
        initComponents();
        lblLuzBaja.setVisible(false);
        lblLuzAlta.setVisible(false);
        lblIntIzq.setVisible(false);
        lblIntDer.setVisible(false);
        lblMotor.setVisible(false);
        lblPuertIzq.setVisible(false);
        lblPuertDer.setVisible(false);
        lblLuzPuertas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMotor = new javax.swing.JToggleButton();
        chkLuzBaja = new javax.swing.JCheckBox();
        chkLuzAlta = new javax.swing.JCheckBox();
        chkIntIzqui = new javax.swing.JCheckBox();
        chkIntDer = new javax.swing.JCheckBox();
        btnEmergencia = new javax.swing.JToggleButton();
        btnPuerDerecha = new javax.swing.JButton();
        lblLuzDer = new javax.swing.JLabel();
        btnPuerIzqui = new javax.swing.JButton();
        lblLuzIz = new javax.swing.JLabel();
        lblLuzBaja = new javax.swing.JLabel();
        lblLuzAlta = new javax.swing.JLabel();
        lblIntDer = new javax.swing.JLabel();
        lblIntIzq = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblPuertIzq = new javax.swing.JLabel();
        lblPuerIzq = new javax.swing.JLabel();
        lblPuertDer = new javax.swing.JLabel();
        lblPuerDer = new javax.swing.JLabel();
        lblLuzPuertas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        btnMotor.setText("Encender Motor");
        btnMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorActionPerformed(evt);
            }
        });

        chkLuzBaja.setBackground(new java.awt.Color(255, 255, 255));
        chkLuzBaja.setText("Luz Baja");
        chkLuzBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzBajaActionPerformed(evt);
            }
        });

        chkLuzAlta.setBackground(new java.awt.Color(255, 255, 255));
        chkLuzAlta.setText("Luz Alta");
        chkLuzAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzAltaActionPerformed(evt);
            }
        });

        chkIntIzqui.setBackground(new java.awt.Color(255, 255, 255));
        chkIntIzqui.setText("Int Izquierda");
        chkIntIzqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntIzquiActionPerformed(evt);
            }
        });

        chkIntDer.setBackground(new java.awt.Color(255, 255, 255));
        chkIntDer.setText("Int Derecha");
        chkIntDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntDerActionPerformed(evt);
            }
        });

        btnEmergencia.setText("Emergencia");
        btnEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergenciaActionPerformed(evt);
            }
        });

        btnPuerDerecha.setText("Abrir/Cerrar PuerDerecha");
        btnPuerDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerDerechaActionPerformed(evt);
            }
        });

        lblLuzDer.setBackground(new java.awt.Color(255, 255, 255));
        lblLuzDer.setText("Luz PuerDerecha OFF");
        lblLuzDer.setOpaque(true);

        btnPuerIzqui.setText("Abrir/Cerrar PuerIzquierda");
        btnPuerIzqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerIzquiActionPerformed(evt);
            }
        });

        lblLuzIz.setBackground(new java.awt.Color(255, 255, 255));
        lblLuzIz.setText("Luz PuerIzquierda OFF");
        lblLuzIz.setOpaque(true);

        lblLuzBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/LuzBaja.png"))); // NOI18N

        lblLuzAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/LuzAlta.png"))); // NOI18N

        lblIntDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/IntDerecha.png"))); // NOI18N

        lblIntIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/IntIzquierda.png"))); // NOI18N

        lblMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Motor.png"))); // NOI18N

        lblPuertIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaAbierta.png"))); // NOI18N

        lblPuerIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaCerrada.png"))); // NOI18N

        lblPuertDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaAbierta.png"))); // NOI18N

        lblPuerDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/PuertaCerrada.png"))); // NOI18N

        lblLuzPuertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconos/Luz.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(chkLuzBaja)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkIntIzqui, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEmergencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(chkLuzAlta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkIntDer, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addGap(352, 352, 352)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPuerIzqui)
                                .addComponent(btnPuerDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIntIzq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLuzDer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuzIz, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMotor)
                    .addComponent(lblMotor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIntDer, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblLuzPuertas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPuertIzq)
                                .addGap(50, 50, 50)
                                .addComponent(lblPuertDer))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPuerIzq)
                                .addGap(50, 50, 50)
                                .addComponent(lblPuerDer))
                            .addComponent(lblLuzAlta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(lblLuzBaja)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntDer)
                    .addComponent(lblIntIzq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(lblLuzPuertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPuerIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuertDer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPuertIzq, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lblPuerDer))
                .addGap(12, 12, 12)
                .addComponent(lblLuzAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblLuzBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuzDer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPuerDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPuerIzqui)
                            .addComponent(lblLuzIz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkLuzAlta)
                            .addComponent(chkIntDer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMotor)
                    .addComponent(chkLuzBaja)
                    .addComponent(chkIntIzqui, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorActionPerformed
        if (!motor.isEstado()) {
            motor.encender();
            btnMotor.setText("Apagar el motor");
            lblMotor.setVisible(true);
        } else {
            motor.apagar();
            btnMotor.setText("Encender el motor");
            chkLuzAlta.setSelected(false);
            chkLuzBaja.setSelected(false);
            chkIntDer.setSelected(false);
            chkIntIzqui.setSelected(false);
            btnEmergencia.setSelected(false);

            luzAlta.apagar();
            luzBaja.apagar();
            intermitentes.apagarEmergencia();
            intermitentes.apagarIntizquierda();
            intermitentes.apagarIntderecha();

            lblMotor.setVisible(false);
            lblLuzAlta.setVisible(false);
            lblLuzBaja.setVisible(false);
            lblIntDer.setVisible(false);
            lblIntIzq.setVisible(false);
        }
    }//GEN-LAST:event_btnMotorActionPerformed

    private void chkLuzBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzBajaActionPerformed
        if (!motor.isEstado()) {
            chkLuzBaja.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la luz baja");
            return;
        }
        if (chkLuzBaja.isSelected()) {
            if (chkLuzAlta.isSelected()) {
                chkLuzAlta.setSelected(false);
                luzAlta.apagar();
                lblLuzAlta.setVisible(false);
            }
            luzBaja.encender(motor);
            lblLuzBaja.setVisible(true);
        } else {
            luzBaja.apagar();
            lblLuzBaja.setVisible(false);
        }
    }//GEN-LAST:event_chkLuzBajaActionPerformed

    private void chkLuzAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzAltaActionPerformed
        if (!motor.isEstado()) {
            chkLuzAlta.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la luz alta");
            return;
        }
        if (chkLuzAlta.isSelected()) {
            if (chkLuzBaja.isSelected()) {
                chkLuzBaja.setSelected(false);
                luzBaja.apagar();
                lblLuzBaja.setVisible(false);
            }
            luzAlta.encender(motor);
            lblLuzAlta.setVisible(true);
        } else {
            luzAlta.apagar();
            lblLuzAlta.setVisible(false);
        }
    }//GEN-LAST:event_chkLuzAltaActionPerformed

    private void btnEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergenciaActionPerformed
        if (!motor.isEstado()) {
            btnEmergencia.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para usar luces de emergencia");
            return;
        }
        if (btnEmergencia.isSelected()) {
            if (chkIntIzqui.isSelected() || chkIntDer.isSelected()) {
                btnEmergencia.setSelected(false);
                javax.swing.JOptionPane.showMessageDialog(this, "Apaga las intermitentes para activar las luces de emergencia");
                return;
            }
            intermitentes.activarEmergencia(motor);
            chkIntIzqui.setSelected(true);
            chkIntDer.setSelected(true);
            btnEmergencia.setText("Apagar emergencia");
            lblIntIzq.setVisible(true);
            lblIntDer.setVisible(true);
        } else {
            intermitentes.apagarEmergencia();
            chkIntIzqui.setSelected(false);
            chkIntDer.setSelected(false);
            btnEmergencia.setText("Encender emergencia");
            lblIntIzq.setVisible(false);
            lblIntDer.setVisible(false);
        }
    }//GEN-LAST:event_btnEmergenciaActionPerformed

    private void chkIntIzquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntIzquiActionPerformed
        if (!motor.isEstado()) {
            chkIntIzqui.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la intermitente izquierda");
            return;
        }
        if (chkIntIzqui.isSelected()) {
            if (chkIntDer.isSelected()) {
                chkIntDer.setSelected(false);
                intermitentes.apagarIntderecha();
                lblIntDer.setVisible(false);
            }
            intermitentes.encenderIntizquierda(motor);
            lblIntIzq.setVisible(true);
        } else {
            intermitentes.apagarIntizquierda();
            lblIntIzq.setVisible(false);
        }
    }//GEN-LAST:event_chkIntIzquiActionPerformed

    private void chkIntDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntDerActionPerformed
        if (!motor.isEstado()) {
            chkIntDer.setSelected(false);
            javax.swing.JOptionPane.showMessageDialog(this, "Enciende el motor para poder usar la intermitente derecha");
            return;
        }
        if (chkIntDer.isSelected()) {
            if (chkIntIzqui.isSelected()) {
                chkIntIzqui.setSelected(false);
                intermitentes.apagarIntizquierda();
                lblIntIzq.setVisible(false);
            }
            intermitentes.encenderIntderecha(motor);
            lblIntDer.setVisible(true);
        } else {
            intermitentes.apagarIntderecha();
            lblIntDer.setVisible(false);
        }   
    }//GEN-LAST:event_chkIntDerActionPerformed

    private void btnPuerIzquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerIzquiActionPerformed
        if (!PuerIzqAbierta) {
            puertaIzq.abrirPuerta();
            lblLuzIz.setText("Luz PuerIzquierda encendida");
            btnPuerIzqui.setText("Cerrar PuerIzquierda");
            PuerIzqAbierta = true;
            lblPuertIzq.setVisible(true);
            lblPuerIzq.setVisible(false); 
        } else {
            puertaIzq.cerrarPuerta();
            lblLuzIz.setText("Luz PuerIzquierda apagada");
            btnPuerIzqui.setText("Abrir PuerIzquierda");
            PuerIzqAbierta = false;
            lblPuertIzq.setVisible(false);
            lblPuerIzq.setVisible(true);
        }
        if (PuerIzqAbierta || PuerDerAbierta) {
            lblLuzPuertas.setVisible(true);
        } else {
            lblLuzPuertas.setVisible(false);
        }
    }//GEN-LAST:event_btnPuerIzquiActionPerformed

    private void btnPuerDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerDerechaActionPerformed
        if (!PuerDerAbierta) {
            puertaDer.abrirPuerta();
            lblLuzDer.setText("Luz PuerDerecha encendida");
            btnPuerDerecha.setText("Cerrar PuerDerecha");
            PuerDerAbierta = true;
            lblPuertDer.setVisible(true);
            lblPuerDer.setVisible(false);
            lblLuzPuertas.setVisible(true);
        } else {
            puertaDer.cerrarPuerta();
            lblLuzDer.setText("Luz PuerDerecha apagada");
            btnPuerDerecha.setText("Abrir PuerDerecha");
            PuerDerAbierta = false;
            lblPuertDer.setVisible(false);
            lblPuerDer.setVisible(true);
            lblLuzPuertas.setVisible(false);
        }
        if (PuerIzqAbierta || PuerDerAbierta) {
            lblLuzPuertas.setVisible(true);
        } else {
            lblLuzPuertas.setVisible(false);
        }
    }//GEN-LAST:event_btnPuerDerechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEmergencia;
    private javax.swing.JToggleButton btnMotor;
    private javax.swing.JButton btnPuerDerecha;
    private javax.swing.JButton btnPuerIzqui;
    private javax.swing.JCheckBox chkIntDer;
    private javax.swing.JCheckBox chkIntIzqui;
    private javax.swing.JCheckBox chkLuzAlta;
    private javax.swing.JCheckBox chkLuzBaja;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblIntDer;
    private javax.swing.JLabel lblIntIzq;
    private javax.swing.JLabel lblLuzAlta;
    private javax.swing.JLabel lblLuzBaja;
    private javax.swing.JLabel lblLuzDer;
    private javax.swing.JLabel lblLuzIz;
    private javax.swing.JLabel lblLuzPuertas;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblPuerDer;
    private javax.swing.JLabel lblPuerIzq;
    private javax.swing.JLabel lblPuertDer;
    private javax.swing.JLabel lblPuertIzq;
    // End of variables declaration//GEN-END:variables
}
